---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstackdomains.sunet.se
spec:
  group: sunet.se
  names:
    kind: OpenstackDomain
    listKind: OpenstackDomainList
    plural: openstackdomains
    singular: openstackdomain
    shortNames:
      - osd
      - osdomain
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Domain
          type: string
          jsonPath: .spec.name
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: "OpenStack domain name"
                  minLength: 1
                  maxLength: 64
                description:
                  type: string
                  description: "Domain description"
                  default: ""
                enabled:
                  type: boolean
                  description: "Whether the domain is enabled"
                  default: true
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Provisioning
                    - Ready
                    - Error
                    - Deleting
                  description: "Current phase of the domain"
                domainId:
                  type: string
                  description: "OpenStack domain ID"
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
                  description: "Generation observed by the controller"
                lastSyncTime:
                  type: string
                  format: date-time
                  description: "Last time the resource was synced"
