---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: openstacknetworks.sunet.se
spec:
  group: sunet.se
  names:
    kind: OpenstackNetwork
    listKind: OpenstackNetworkList
    plural: openstacknetworks
    singular: openstacknetwork
    shortNames:
      - osn
      - osnet
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Network
          type: string
          jsonPath: .spec.name
        - name: External
          type: boolean
          jsonPath: .spec.external
        - name: Type
          type: string
          jsonPath: .spec.providerNetworkType
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: "OpenStack network name"
                  minLength: 1
                  maxLength: 255
                description:
                  type: string
                  description: "Network description"
                  default: ""
                external:
                  type: boolean
                  description: "Whether this is an external network"
                  default: false
                shared:
                  type: boolean
                  description: "Whether the network is shared across all projects"
                  default: false
                providerNetworkType:
                  type: string
                  description: "Provider network type"
                  enum:
                    - flat
                    - vlan
                    - vxlan
                    - gre
                    - geneve
                providerPhysicalNetwork:
                  type: string
                  description: "Physical network for provider networks"
                providerSegmentationId:
                  type: integer
                  description: "Segmentation ID (VLAN ID, VXLAN VNI, etc.)"
                  minimum: 1
                subnets:
                  type: array
                  description: "Subnets to create in this network"
                  items:
                    type: object
                    required:
                      - name
                      - cidr
                    properties:
                      name:
                        type: string
                        description: "Subnet name"
                        minLength: 1
                      cidr:
                        type: string
                        description: "Subnet CIDR (e.g., 192.168.100.0/24)"
                        pattern: "^([0-9]{1,3}\\.){3}[0-9]{1,3}/[0-9]{1,2}$"
                      gatewayIp:
                        type: string
                        description: "Gateway IP address"
                      enableDhcp:
                        type: boolean
                        description: "Whether to enable DHCP"
                        default: true
                      dnsNameservers:
                        type: array
                        description: "DNS nameservers"
                        items:
                          type: string
                      allocationPools:
                        type: array
                        description: "IP allocation pools"
                        items:
                          type: object
                          required:
                            - start
                            - end
                          properties:
                            start:
                              type: string
                              description: "Start IP of the pool"
                            end:
                              type: string
                              description: "End IP of the pool"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Provisioning
                    - Ready
                    - Error
                    - Deleting
                  description: "Current phase of the network"
                networkId:
                  type: string
                  description: "OpenStack network ID"
                subnets:
                  type: array
                  description: "Status of created subnets"
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      subnetId:
                        type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                observedGeneration:
                  type: integer
                  description: "Generation observed by the controller"
                lastSyncTime:
                  type: string
                  format: date-time
                  description: "Last time the resource was synced"
