---
# ServiceMonitor for Prometheus Operator
# Only apply if you have Prometheus Operator installed
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openstack-operator
  labels:
    app.kubernetes.io/name: openstack-operator
    app.kubernetes.io/component: operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openstack-operator
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
